### ISSUE TITLE
Erro ao rodar aplicação Go

### ISSUE THREAD

**Issue by DaniSangelo** [devfullcycle/imersao15#17]
Olá, pessoal. A versão do meu **docker-compose** e do meu **dockerfile** está como no commit da aula 2. Porém, quando rodo o comando `go run cmd/main.go` aparece o seguinte erro: 

../pkg/mod/golang.org/x/net@v0.14.0/http2/transport.go:19:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)

![image](https://github.com/devfullcycle/imersao15/assets/57871941/770da7fd-4d01-4c97-982e-9b285d41bd9c)

Também fiz as modificações propostas na página inicial do repositório (mudando o go para 1.19), mas mesmo assim não funcionou, e a versão do go continua na 1.15

Meu ambiente é o WSL 2, rodando o Ubuntu no Windows

Docker version 24.0.6

**Comment by Prudhvi-232** [comment]
hey @DaniSangelo assign me this i will explain clearly 
1.change your Go version to 1.19 your present version is 1.15 you can check your version by running 'go version'

**Comment by DaniSangelo** [comment]
> hey @DaniSangelo assign me this i will explain clearly 1.change your Go version to 1.19 your present version is 1.15 you can check your version by running 'go version'

Hi, @Prudhvi-232 , fortunately, I could fix it. First, I ran `docker compose down`, and then `docker-compose up -d --build` to rebuild the go's image, and _voila_. Thank you very much. Closing this issue

**Comment by Prudhvi-232** [comment]
@DaniSangelo your pleasure
